### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by brokkr** [asyncopation/ttrss-theme-chalk#4]
The repository does not contain a notice saying how the code is licensed.

Bit of a github noob here. I have forked the repo and have done some local changes for my personal benefit but before I push them back to my fork I just want to know that that is 'allowed' :-)

[This stackoverflow answer] (http://stackoverflow.com/a/13669816) seems to indicate that without an explicit license the default is an 'all rights reserved' use of copyright.

**Comment by asyncopation** [comment]
Hey thanks for bringing this to my attention.  Added LICENSE file GPLv3.

**Comment by brokkr** [comment]
Cool, thanks. I'll do the same on the fork
